[pools.main]
spec = { type = "main" }

[[graph.nodes]]
name = "double"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.double" }
execution_config = { pools = ["main"] }

[[graph.nodes]]
name = "add"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.add" }
execution_config = { pools = ["remote"] }

[[graph.nodes]]
name = "format_result"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.format_result" }
execution_config = { pools = ["main"] }

[[graph.edges]]
source_str = "double.out"
target_str = "add.a"

[[graph.edges]]
source_str = "add.out"
target_str = "format_result.value"

[output_queues.results]
ports = [["format_result", "out"]]
