[pools.main]
spec = { type = "main" }

[pools.remote]
spec = { type = "remote", num_processes = 1, threads_per_process = 1 }

[[graph.nodes]]
name = "double"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.double" }
execution_config = { pools = ["main"] }

[[graph.nodes]]
name = "add"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.add" }
execution_config = { pools = ["remote"] }

[[graph.nodes]]
name = "format_result"
factory = "netrun.node_factories.from_function"
factory_args = { func = "nodes.format_result" }
execution_config = { pools = ["main"] }

[[graph.edges]]
source_node = "double"
source_port = "out"
target_node = "add"
target_port = "a"

[[graph.edges]]
source_node = "add"
source_port = "out"
target_node = "format_result"
target_port = "value"

[output_queues.results]
ports = [["format_result", "out"]]
