# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/07_node_factories/test_join.pct.py

__all__ = ['test_default_config', 'test_dict_ports', 'test_duplicate_port_names_raises', 'test_empty_dict_raises', 'test_empty_list_raises', 'test_get_node_funcs_returns_tuple', 'test_invalid_ports_type_raises', 'test_join_batch_port', 'test_join_two_sources', 'test_list_ports', 'test_negative_count_raises', 'test_output_salvo', 'test_single_port', 'test_trigger_salvo_structure_batch', 'test_trigger_salvo_structure_scalar', 'test_zero_count_raises']

# %% pts/tests/07_node_factories/test_join.pct.py 2
import pytest
from netrun.node_factories.join import (
    get_node_config,
    get_node_funcs,
    _normalise_ports,
)
from netrun.net.config import (
    SalvoConditionTermAndConfig,
    SalvoConditionTermPortConfig,
    PortStateNonEmptyConfig,
    PortStateEqualsOrGreaterThanConfig,
    PacketCountNConfig,
    PacketCountAllConfig,
)

# %% pts/tests/07_node_factories/test_join.pct.py 4
def test_default_config():
    """Default ports=("a","b"), both count=1."""
    config = get_node_config()
    assert config.name == "join"
    assert list(config.in_ports.keys()) == ["a", "b"]
    assert list(config.out_ports.keys()) == ["out"]
    assert config.execution_config is None


def test_list_ports():
    """List of port names, each count=1."""
    config = get_node_config(ports=["x", "y", "z"])
    assert list(config.in_ports.keys()) == ["x", "y", "z"]
    assert list(config.out_ports.keys()) == ["out"]


def test_dict_ports():
    """Dict of port names with explicit counts."""
    config = get_node_config(ports={"data": 1, "batch": 3})
    assert list(config.in_ports.keys()) == ["data", "batch"]


def test_single_port():
    """Join with a single port is valid (degenerate case)."""
    config = get_node_config(ports=["only"])
    assert list(config.in_ports.keys()) == ["only"]

# %% pts/tests/07_node_factories/test_join.pct.py 6
def test_trigger_salvo_structure_scalar():
    """All count=1 ports use NonEmpty state."""
    config = get_node_config(ports=["a", "b"])
    trigger = config.in_salvo_conditions["trigger"]

    assert isinstance(trigger.term, SalvoConditionTermAndConfig)
    assert len(trigger.term.terms) == 2

    for term in trigger.term.terms:
        assert isinstance(term, SalvoConditionTermPortConfig)
        assert isinstance(term.state, PortStateNonEmptyConfig)

    assert trigger.ports == {
        "a": PacketCountNConfig(count=1),
        "b": PacketCountNConfig(count=1),
    }
    assert trigger.max_salvos.max == 1


def test_trigger_salvo_structure_batch():
    """Ports with count>1 use EqualsOrGreaterThan state."""
    config = get_node_config(ports={"single": 1, "multi": 3})
    trigger = config.in_salvo_conditions["trigger"]

    assert isinstance(trigger.term, SalvoConditionTermAndConfig)
    terms_by_port = {t.port_name: t for t in trigger.term.terms}

    assert isinstance(terms_by_port["single"].state, PortStateNonEmptyConfig)
    assert isinstance(terms_by_port["multi"].state, PortStateEqualsOrGreaterThanConfig)
    assert terms_by_port["multi"].state.value == 3

    assert trigger.ports["single"] == PacketCountNConfig(count=1)
    assert trigger.ports["multi"] == PacketCountNConfig(count=3)


def test_output_salvo():
    """Output salvo sends all from 'out' port."""
    config = get_node_config(ports=["a"])
    send = config.out_salvo_conditions["send"]
    assert "out" in send.ports
    assert isinstance(send.ports["out"], PacketCountAllConfig)

# %% pts/tests/07_node_factories/test_join.pct.py 8
def test_empty_list_raises():
    with pytest.raises(ValueError, match="empty"):
        get_node_config(ports=[])


def test_empty_dict_raises():
    with pytest.raises(ValueError, match="empty"):
        get_node_config(ports={})


def test_duplicate_port_names_raises():
    with pytest.raises(ValueError, match="duplicate"):
        get_node_config(ports=["a", "b", "a"])


def test_zero_count_raises():
    with pytest.raises(ValueError, match="count"):
        get_node_config(ports={"a": 0})


def test_negative_count_raises():
    with pytest.raises(ValueError, match="count"):
        get_node_config(ports={"a": -1})


def test_invalid_ports_type_raises():
    with pytest.raises(TypeError, match="list.*dict"):
        get_node_config(ports=42)

# %% pts/tests/07_node_factories/test_join.pct.py 10
def test_get_node_funcs_returns_tuple():
    funcs = get_node_funcs(ports=["a", "b"])
    assert len(funcs) == 4
    assert callable(funcs[0])
    assert funcs[1] is None
    assert funcs[2] is None
    assert funcs[3] is None

# %% pts/tests/07_node_factories/test_join.pct.py 12
from netrun.net.config import (
    NetConfig,
    NodeConfig as NC,
    NodeExecutionConfig,
    PortConfig,
    GraphConfig,
    EdgeConfig,
    SalvoConditionConfig,
    SalvoConditionTermTrueConfig,
    MaxSalvosFiniteConfig,
    PacketCountAllConfig as PCA,
    PacketCountNConfig as PCN,
    PoolConfig,
    OutputQueueConfig,
)
from netrun.net.config._net_config import MainPoolConfig
from netrun.net._net._net import Net


def _source_exec(value):
    """Create an exec function that outputs a fixed value."""
    def exec_func(ctx, packets):
        for pid in packets.get("trigger", []):
            ctx.consume_packet(pid)
        p = ctx.create_packet(value)
        ctx.load_output_port("out", p)
        ctx.send_output_salvo("send")
    return exec_func


def _source_node(name: str, exec_func, out_port: str = "out") -> NC:
    """A trivial source node with one output port and an exec function."""
    return NC(
        name=name,
        in_ports={"trigger": PortConfig()},
        out_ports={out_port: PortConfig()},
        in_salvo_conditions={
            "go": SalvoConditionConfig(
                max_salvos=MaxSalvosFiniteConfig(max=1),
                ports={"trigger": PCN(count=1)},
                term=SalvoConditionTermTrueConfig(),
            ),
        },
        out_salvo_conditions={
            "send": SalvoConditionConfig(
                max_salvos=MaxSalvosFiniteConfig(max=1),
                ports={out_port: PCA()},
                term=SalvoConditionTermTrueConfig(),
            ),
        },
        execution_config=NodeExecutionConfig(
            node_name=name,
            pools=["main"],
            exec_node_func=exec_func,
        ),
    )


def _join_node_with_exec(ports):
    """Create a join NodeConfig with its exec function attached."""
    join_cfg = get_node_config(ports=ports)
    join_exec = get_node_funcs(ports=ports)[0]
    join_cfg.execution_config = NodeExecutionConfig(
        node_name="join",
        pools=["main"],
        exec_node_func=join_exec,
    )
    return join_cfg

# %% pts/tests/07_node_factories/test_join.pct.py 13
@pytest.mark.asyncio
async def test_join_two_sources():
    """Two sources feed into a join; output is a dict of their values."""
    config = NetConfig(
        pools={"main": PoolConfig(spec=MainPoolConfig())},
        graph=GraphConfig(
            nodes=[
                _source_node("src_a", _source_exec("hello")),
                _source_node("src_b", _source_exec(42)),
                _join_node_with_exec(["left", "right"]),
            ],
            edges=[
                EdgeConfig(source_str="src_a.out", target_str="join.left"),
                EdgeConfig(source_str="src_b.out", target_str="join.right"),
            ],
        ),
        output_queues={"results": OutputQueueConfig(ports=[("join", "out")])},
    )

    async with Net(config) as net:
        net.inject_data("src_a", "trigger", [None])
        net.inject_data("src_b", "trigger", [None])

        await net.run_until_blocked()

        results = net.flush_output_queue("results")
        assert len(results) == 1
        assert results[0] == {"left": "hello", "right": 42}

# %% pts/tests/07_node_factories/test_join.pct.py 14
@pytest.mark.asyncio
async def test_join_batch_port():
    """A join port with count>1 collects multiple packets into a list."""
    def src_batch_exec(ctx, packets):
        for pid in packets.get("trigger", []):
            ctx.consume_packet(pid)
        for val in ["first", "second"]:
            p = ctx.create_packet(val)
            ctx.load_output_port("out", p)
        ctx.send_output_salvo("send")

    config = NetConfig(
        pools={"main": PoolConfig(spec=MainPoolConfig())},
        graph=GraphConfig(
            nodes=[
                _source_node("src_scalar", _source_exec("only_one")),
                _source_node("src_batch", src_batch_exec),
                _join_node_with_exec({"scalar": 1, "batch": 2}),
            ],
            edges=[
                EdgeConfig(source_str="src_scalar.out", target_str="join.scalar"),
                EdgeConfig(source_str="src_batch.out", target_str="join.batch"),
            ],
        ),
        output_queues={"results": OutputQueueConfig(ports=[("join", "out")])},
    )

    async with Net(config) as net:
        net.inject_data("src_scalar", "trigger", [None])
        net.inject_data("src_batch", "trigger", [None])

        await net.run_until_blocked()

        results = net.flush_output_queue("results")
        assert len(results) == 1
        assert results[0]["scalar"] == "only_one"
        assert isinstance(results[0]["batch"], list)
        assert len(results[0]["batch"]) == 2
        assert set(results[0]["batch"]) == {"first", "second"}
