# AUTOGENERATED! DO NOT EDIT! File to edit: pts/netrun/05_execution_manager.pct.py

__all__ = ['ExecutionManager', 'ExecutionManagerProtocolKeys', 'JobResult', 'PoolType', 'RunAllocationMethod', 'SubmittedJobInfo', 'create_execution_manager_server', 'remote_execution_manager_worker', 'to_picklable_exception']

# %% pts/netrun/05_execution_manager.pct.py 3
from typing import Any
from collections.abc import Callable, Awaitable
from ._iutils import get_timestamp_utc
from datetime import datetime
import asyncio
import logging
import threading
from enum import Enum
from dataclasses import dataclass
import importlib
import uuid
import pickle
import random
import functools

from .pool.base import POOL_UP_ERROR_KEYS, _check_error_and_raise
from .pool.thread import ThreadPool
from .pool.multiprocess import MultiprocessPool
from .pool.aio import SingleWorkerPool
from .pool.remote import RemotePoolClient

# %% pts/netrun/05_execution_manager.pct.py 5
async def _async_func_runner(
    func: Callable[..., Awaitable[Any]],
    args: tuple,
    kwargs: dict,
) -> Any:
    if asyncio.iscoroutinefunction(func):
        return await func(*args, **kwargs)
    else:
        return func(*args, **kwargs)

# %% pts/netrun/05_execution_manager.pct.py 6
def _func_runner(
    func: Callable[..., Any],
    args: tuple,
    kwargs: dict,
    shared_loop: asyncio.AbstractEventLoop | None = None,
) -> Any:
    """Run a function (sync or async) in a worker thread.

    When a func_preprocessor is used, it returns a sync wrapper that handles
    async dispatch internally. When called directly without a preprocessor,
    async functions are submitted to the shared event loop.
    """
    if asyncio.iscoroutinefunction(func):
        coro = func(*args, **kwargs)
        if shared_loop is not None:
            future = asyncio.run_coroutine_threadsafe(coro, shared_loop)
            return future.result()
        else:
            # Fallback: create a temporary event loop (for backward compat)
            loop = asyncio.new_event_loop()
            try:
                return loop.run_until_complete(coro)
            finally:
                loop.close()
    else:
        return func(*args, **kwargs)

# %% pts/netrun/05_execution_manager.pct.py 8
_worker_state = threading.local()
"""Thread-local state for worker threads.

Attributes set by _worker_func on startup:
    shared_loop: The shared event loop for async function dispatch.
        Read by NetFuncPreprocessor.call_for_sync_worker() to submit
        async user functions via run_coroutine_threadsafe().
"""

# %% pts/netrun/05_execution_manager.pct.py 10
def _convert_to_str_if_not_serializable(obj: Any) -> tuple[bool, Any]:
    """Convert an object to string if it's not pickle-serializable.

    Returns:
        Tuple of (was_converted, result)
    """
    try:
        pickle.dumps(obj)
        return (False, obj)
    except (pickle.PicklingError, TypeError, AttributeError):
        return (True, str(obj))

# %% pts/netrun/05_execution_manager.pct.py 11
def to_picklable_exception(e: BaseException) -> BaseException:
    """Return `e` unchanged if it's pickle-serializable, otherwise a serializable
    proxy.

    Worker error paths must always send a terminal `UP_RUN_RESPONSE` so the client
    doesn't hang. If the user (or some library) raises an exception that holds an
    unpicklable attribute (lambda, generator, traceback, open file handle, …), the
    raw exception cannot cross a multiprocess boundary. We replace it with a
    `RuntimeError` whose message preserves the original type name and `repr`, so
    the caller still gets an `Exception` it can `raise`.
    """
    try:
        pickle.dumps(e)
        return e
    except (pickle.PicklingError, TypeError, AttributeError) as pickle_err:
        return RuntimeError(
            f"<unpicklable {type(e).__name__}: {e!r}> "
            f"(pickle error: {pickle_err!r})"
        )

# %% pts/netrun/05_execution_manager.pct.py 13
class ExecutionManagerProtocolKeys(Enum):
    RUN = "exec-manager:run"
    """
    Run a function.
    Args: msg_id, func_import_path_or_key, run_id, args, kwargs
    """

    UP_RUN_RESPONSE = "exec-manager-up:run-response"
    """
    Response to RUN from the worker.
    Args: msg_id, timestamp_utc_started, timestamp_utc_completed, converted_to_str, _res
    """

    SEND_FUNCTION = "exec-manager:send-function"
    """
    Used to send a function object to the worker, which can then be run using RUN.
    Args: msg_id, func_key, func
    """

    UP_SEND_FUNCTION_RESPONSE = "exec-manager-up:send-function-response"
    """
    Response to SEND_FUNCTION from the worker, to confirm that the function was received.
    Args: msg_id
    """

# %% pts/netrun/05_execution_manager.pct.py 14
def _worker_func(
    is_in_main_process: bool,
    channel,
    worker_id,
    func_preprocessor: Callable | None = None,
    func_done_callback: Callable | None = None,
    shared_loop: asyncio.AbstractEventLoop | None = None,
):
    """Worker function that handles execution manager protocol messages.

    Args:
        is_in_main_process: If True, results don't need to be serializable.
        channel: RPC channel for communication.
        worker_id: ID of this worker.
        func_preprocessor: If provided, preprocesses the function before execution.
            Uses call_for_sync_worker() for sync dispatch with shared_loop for async.
        func_done_callback: If provided, called after function execution.
        shared_loop: Shared event loop for async function dispatch. Async user
            functions are submitted to this loop via run_coroutine_threadsafe().
    """
    # Set shared loop on thread-local so the preprocessor's sync wrapper can
    # dispatch async functions via run_coroutine_threadsafe(). This avoids
    # mutating the preprocessor instance (which must stay picklable for
    # multiprocess pools).
    _worker_state.shared_loop = shared_loop

    registered_functions: dict[str, Callable[..., Awaitable] | Callable[..., None]] = {}

    while True:
        key, data = channel.recv()
        # RUN
        if key == ExecutionManagerProtocolKeys.RUN.value:
            msg_id, func_import_path_or_key, run_id, args, kwargs = data
            timestamp_utc_started = None
            try:
                if func_import_path_or_key in registered_functions:
                    func = registered_functions[func_import_path_or_key]
                else:
                    module_path, func_name = func_import_path_or_key.rsplit(".", 1)
                    module = importlib.import_module(module_path)
                    func = getattr(module, func_name)

                if func_preprocessor is not None:
                    func = func_preprocessor.call_for_sync_worker(func)

                timestamp_utc_started = get_timestamp_utc()
                res = _func_runner(
                    func=func,
                    args=args,
                    kwargs=kwargs,
                    shared_loop=shared_loop,
                )

                # Call done callback if provided
                if func_done_callback is not None:
                    func_done_callback(*args, **kwargs, result=res)

                timestamp_utc_completed = get_timestamp_utc()
                if is_in_main_process:
                    converted_to_str, _res = False, res
                else:
                    converted_to_str, _res = _convert_to_str_if_not_serializable(res)

                channel.send(ExecutionManagerProtocolKeys.UP_RUN_RESPONSE.value, (msg_id, timestamp_utc_started, timestamp_utc_completed, converted_to_str, _res))
            except Exception as e:
                # Send error response so the client doesn't hang forever.
                # Sanitize first: a non-picklable exception would otherwise
                # blow up channel.send() across a multiprocess boundary, the
                # except below would swallow the PicklingError, and the caller
                # would block forever waiting for UP_RUN_RESPONSE.
                timestamp_utc_error = get_timestamp_utc()
                if timestamp_utc_started is None:
                    timestamp_utc_started = timestamp_utc_error
                err = to_picklable_exception(e)
                try:
                    channel.send(ExecutionManagerProtocolKeys.UP_RUN_RESPONSE.value, (msg_id, timestamp_utc_started, timestamp_utc_error, False, err))
                except Exception as send_err:
                    # Last-ditch: the channel itself is broken. Log so this
                    # doesn't manifest as a silent hang.
                    _logger = logging.getLogger("netrun.execution_manager")
                    _logger.error(
                        "Worker %s failed to deliver error response for run %s: %r",
                        worker_id, run_id, send_err,
                    )
        # SEND_FUNCTION
        elif key == ExecutionManagerProtocolKeys.SEND_FUNCTION.value:
            msg_id, func_key, func = data
            registered_functions[func_key] = func
            channel.send(ExecutionManagerProtocolKeys.UP_SEND_FUNCTION_RESPONSE.value, (msg_id,))
        else:
            raise ValueError(f"Unknown execution manager protocol key: '{key}'.")

# %% pts/netrun/05_execution_manager.pct.py 15
async def _async_worker_func(
    channel,
    worker_id,
    func_preprocessor: Callable | None = None,
    func_done_callback: Callable | None = None,
):
    """Async worker function that handles execution manager protocol messages.

    Spawns each RUN request as a concurrent asyncio.Task so multiple async
    functions execute concurrently on the event loop (instead of serializing).

    Args:
        channel: Async RPC channel for communication.
        worker_id: ID of this worker.
        func_preprocessor: If provided, this is a function that preprocesses the function before it is executed.
        func_done_callback: If provided, this is called after function execution with the same args/kwargs
            that were passed to the function, plus the result. Can be sync or async.
    """
    registered_functions: dict[str, Callable[..., Awaitable] | Callable[..., None]] = {}

    async def _handle_run(msg_id, func, args, kwargs):
        """Execute a single RUN request and send the response."""
        timestamp_utc_started = get_timestamp_utc()
        try:
            res = await _async_func_runner(
                func=func,
                args=args,
                kwargs=kwargs,
            )

            # Call done callback if provided
            if func_done_callback is not None:
                callback_result = func_done_callback(*args, **kwargs, result=res)
                # Await if the callback is async
                if asyncio.iscoroutine(callback_result):
                    await callback_result

            timestamp_utc_completed = get_timestamp_utc()
            converted_to_str, _res = False, res

            await channel.send(ExecutionManagerProtocolKeys.UP_RUN_RESPONSE.value, (msg_id, timestamp_utc_started, timestamp_utc_completed, converted_to_str, _res))
        except Exception as e:
            # Send error response so the client doesn't hang forever.
            # See to_picklable_exception() — sanitize before sending across
            # process boundaries.
            timestamp_utc_error = get_timestamp_utc()
            err = to_picklable_exception(e)
            try:
                await channel.send(ExecutionManagerProtocolKeys.UP_RUN_RESPONSE.value, (msg_id, timestamp_utc_started, timestamp_utc_error, False, err))
            except Exception as send_err:
                _logger = logging.getLogger("netrun.execution_manager")
                _logger.error(
                    "Async worker %s failed to deliver error response for msg %s: %r",
                    worker_id, msg_id, send_err,
                )

    pending_tasks: set[asyncio.Task] = set()

    try:
        while True:
            key, data = await channel.recv()
            # RUN
            if key == ExecutionManagerProtocolKeys.RUN.value:
                msg_id, func_import_path_or_key, run_id, args, kwargs = data
                if func_import_path_or_key in registered_functions:
                    func = registered_functions[func_import_path_or_key]
                else:
                    module_path, func_name = func_import_path_or_key.rsplit(".", 1)
                    module = importlib.import_module(module_path)
                    func = getattr(module, func_name)

                if func_preprocessor is not None:
                    func = func_preprocessor(func)

                # Spawn as concurrent task instead of awaiting inline
                task = asyncio.create_task(_handle_run(msg_id, func, args, kwargs))
                pending_tasks.add(task)
                task.add_done_callback(pending_tasks.discard)
            # SEND_FUNCTION
            elif key == ExecutionManagerProtocolKeys.SEND_FUNCTION.value:
                msg_id, func_key, func = data
                registered_functions[func_key] = func
                await channel.send(ExecutionManagerProtocolKeys.UP_SEND_FUNCTION_RESPONSE.value, (msg_id,))
            else:
                raise ValueError(f"Unknown execution manager protocol key: '{key}'.")
    finally:
        # Cancel any still-running tasks on shutdown
        for task in pending_tasks:
            task.cancel()
        if pending_tasks:
            await asyncio.gather(*pending_tasks, return_exceptions=True)

# %% pts/netrun/05_execution_manager.pct.py 17
def remote_execution_manager_worker(
    channel,
    worker_id: int,
    func_preprocessor: Callable | None = None,
    func_done_callback: Callable | None = None,
    shared_loop: asyncio.AbstractEventLoop | None = None,
) -> None:
    return _worker_func(
        is_in_main_process=False,
        channel=channel,
        worker_id=worker_id,
        func_preprocessor=func_preprocessor,
        func_done_callback=func_done_callback,
        shared_loop=shared_loop,
    )

# %% pts/netrun/05_execution_manager.pct.py 18
def create_execution_manager_server(
    worker_name: str = "execution_manager",
    func_preprocessor: Callable | None = None,
    func_done_callback: Callable | None = None,
):
    """Create a RemotePoolServer configured for ExecutionManager.

    This is a convenience function that creates a RemotePoolServer with
    the `remote_execution_manager_worker` already registered.

    Example - Blocking server:
        ```python
        from netrun.execution_manager import create_execution_manager_server

        server = create_execution_manager_server()
        await server.serve("0.0.0.0", 8080)
        ```

    Example - Background server:
        ```python
        server = create_execution_manager_server()
        async with server.serve_background("0.0.0.0", 8080):
            # Server is running, do other work...
            await asyncio.sleep(3600)
        ```

    Example - Client connection:
        ```python
        from netrun.execution_manager import ExecutionManager, create_execution_manager_server
        from netrun.pool.remote import RemotePoolClient

        # On server:
        server = create_execution_manager_server(worker_name="my_worker")
        await server.serve("0.0.0.0", 8080)

        # On client:
        manager = ExecutionManager({
            "remote": (RemotePoolClient, {
                "url": "ws://server:8080",
                "worker_name": "my_worker",
                "num_processes": 4,
            }),
        })
        async with manager:
            await manager.send_function_to_pool("remote", "fn", my_function)
            result = await manager.run(...)
        ```

    Args:
        worker_name: Name to register the worker under. Clients must use this
            name when connecting (via `worker_name` parameter in RemotePoolClient).
        func_preprocessor: If provided, preprocesses functions before execution.
        func_done_callback: If provided, called after function execution completes.

    Returns:
        A configured RemotePoolServer ready to serve.
    """
    from .pool.remote import RemotePoolServer
    import functools

    server = RemotePoolServer()
    worker_fn = functools.partial(
        remote_execution_manager_worker,
        func_preprocessor=func_preprocessor,
        func_done_callback=func_done_callback,
    )
    server.register_worker(worker_name, worker_fn)
    return server

# %% pts/netrun/05_execution_manager.pct.py 20
@dataclass
class JobResult:
    """Result of a job execution."""
    timestamp_utc_submitted: datetime
    timestamp_utc_started: datetime
    timestamp_utc_completed: datetime
    func_import_path_or_key: str
    pool_id: str
    worker_id: int
    converted_to_str: bool
    result: Any

@dataclass
class SubmittedJobInfo:
    """Information about a submitted job."""
    run_id: str
    timestamp_utc_submitted: datetime
    timestamp_utc_started: datetime | None
    func_import_path_or_key: str
    pool_id: str
    worker_id: int

class RunAllocationMethod(Enum):
    """Method for allocating a job to a worker."""
    ROUND_ROBIN = "round-robin"
    RANDOM = "random"
    LEAST_BUSY = "least-busy"

# %% pts/netrun/05_execution_manager.pct.py 21
PoolType = ThreadPool | MultiprocessPool | SingleWorkerPool | RemotePoolClient

class ExecutionManager:
    """High-level orchestrator for executing functions across pools.

    Wraps one or more pools (`ThreadPool`, `MultiprocessPool`, `SingleWorkerPool`,
    `RemotePoolClient`) and routes function execution requests to specific
    workers, tracking per-job lifecycle.

    Each submitted job produces exactly one terminal event (`UP_RUN_RESPONSE`),
    which carries the result, both timestamps (started, completed), and any
    captured print output. Worker crashes are isolated: a crashed worker only
    fails the jobs targeting it, leaving the rest of the pool intact.

    Async functions dispatched to thread/multiprocess workers run on a single
    **shared event loop** owned by the manager (one daemon thread per process
    scope). Sync functions run directly on the worker thread/process. This
    makes `asyncio.create_subprocess_exec`, nested awaits, and cross-node
    `asyncio.Lock` work without per-worker loop hacks.
    """

    def __init__(self, pool_configs: dict[str, tuple[type[PoolType], dict[str, Any]]]):
        """
        Create an ExecutionManager with the given pool configurations.

        Args:
            pool_configs: A dictionary mapping pool_id to (pool_type, pool_init_kwargs).
                pool_type can be `ThreadPool`, `MultiprocessPool`, `SingleWorkerPool`,
                or `RemotePoolClient`. pool_init_kwargs are passed to the pool
                constructor (excluding worker_fn).
        """
        self._pool_configs = pool_configs
        self._pools: dict[str, PoolType] = {}
        self._msg_recv_tasks: dict[str, asyncio.Task] = {}
        self._msgs: dict[str, dict[str, asyncio.Queue]] = {}
        self._started = False

        self._worker_jobs: dict[tuple[str, str], list[SubmittedJobInfo]] = {}  # (pool_id, worker_id) -> list of SubmittedJobInfo
        self._round_robin_counter: int = 0
        self._msg_worker_map: dict[str, dict[str, int]] = {}  # pool_id -> {msg_id -> worker_id}

        # Shared event loop for async function dispatch in thread/multiprocess workers.
        # Created in start(), cleaned up in close().
        self._shared_loop: asyncio.AbstractEventLoop | None = None
        self._shared_loop_thread: threading.Thread | None = None

    async def start(self) -> None:
        """Start all pools and initialize the execution manager."""
        if self._started:
            raise RuntimeError("ExecutionManager is already started.")

        # Create shared event loop on a dedicated daemon thread.
        # Thread pool workers submit async coroutines to this loop via
        # run_coroutine_threadsafe(). This replaces the broken per-thread
        # event loops that lacked child watchers and couldn't share asyncio
        # primitives across workers.
        self._shared_loop = asyncio.new_event_loop()
        self._shared_loop_thread = threading.Thread(
            target=self._shared_loop.run_forever,
            daemon=True,
            name="netrun-shared-async-loop",
        )
        self._shared_loop_thread.start()

        for pool_id, (pool_type, pool_init_kwargs) in self._pool_configs.items():
            if 'worker_fn' in pool_init_kwargs:
                raise ValueError("The 'worker_fn' argument should not be specified in the pool config.")

            pool_kwargs = dict(pool_init_kwargs)
            func_preprocessor = pool_kwargs.pop('func_preprocessor', None)
            func_done_callback = pool_kwargs.pop('func_done_callback', None)

            if pool_type == ThreadPool:
                worker_fn = functools.partial(_worker_func, True, func_preprocessor=func_preprocessor, func_done_callback=func_done_callback, shared_loop=self._shared_loop)
                self._pools[pool_id] = ThreadPool(**pool_kwargs, worker_fn=worker_fn)
            elif pool_type == MultiprocessPool:
                # Multiprocess workers create their own process-local shared loop
                # (event loops can't cross process boundaries)
                worker_fn = functools.partial(_worker_func, False, func_preprocessor=func_preprocessor, func_done_callback=func_done_callback)
                self._pools[pool_id] = MultiprocessPool(**pool_kwargs, worker_fn=worker_fn)
            elif pool_type == RemotePoolClient:
                self._pools[pool_id] = RemotePoolClient(**pool_kwargs)
            elif pool_type == SingleWorkerPool:
                # SingleWorkerPool runs on the main event loop — no shared loop needed
                worker_fn = functools.partial(_async_worker_func, func_preprocessor=func_preprocessor, func_done_callback=func_done_callback)
                self._pools[pool_id] = SingleWorkerPool(**pool_kwargs, worker_fn=worker_fn)
            else:
                raise ValueError(f"Unknown pool type: '{pool_type}'.")

            self._msgs[pool_id] = {}

        # Start all pools
        for pool_id, pool in self._pools.items():
            await pool.start()

        # Initialize worker jobs tracking for each worker
        for pool_id, pool in self._pools.items():
            for worker_id in range(pool.num_workers):
                self._worker_jobs[(pool_id, worker_id)] = []

        # Start message receiver tasks after pools are started
        for pool_id in self._pools:
            self._msg_recv_tasks[pool_id] = asyncio.create_task(self._msg_recv_task_func(pool_id))

        self._started = True

    async def _msg_recv_task_func(self, pool_id: str):
        pool = self._pools[pool_id]
        while True:
            msg = await pool.recv_raw()

            # Pool-level error (worker crashed/died) — route to affected jobs
            # instead of crashing the entire receiver task.
            if msg.key in POOL_UP_ERROR_KEYS:
                worker_id = msg.worker_id
                affected_msg_ids = [
                    mid for mid, wid in self._msg_worker_map.get(pool_id, {}).items()
                    if wid == worker_id
                ]
                for mid in affected_msg_ids:
                    queue = self._msgs[pool_id].get(mid)
                    if queue is not None:
                        await queue.put(msg)
                continue

            # Normal message — route by msg_id
            msg_id = msg.data[0]
            msg.data = msg.data[1:]
            queue = self._msgs[pool_id].get(msg_id)
            if queue is not None:
                await queue.put(msg)


    async def _send_msg(self, pool_id: str, worker_id: str, key: str, data: Any) -> str:
        pool = self._pools[pool_id]
        msg_id = str(uuid.uuid4())

        # Check if the message receiver task for the pool is running, else propagate its exception
        msg_recv_task = self._msg_recv_tasks.get(pool_id)
        if msg_recv_task is not None and msg_recv_task.done():
            exc = msg_recv_task.exception()
            if exc is not None:
                raise exc

        # Create the queue BEFORE sending to avoid race condition where response
        # arrives before the queue is created
        self._msgs[pool_id][msg_id] = asyncio.Queue()
        # Track which worker this msg_id is for (needed to route worker errors)
        self._msg_worker_map.setdefault(pool_id, {})[msg_id] = worker_id

        await pool.send(
            worker_id=worker_id,
            key=key,
            data=(msg_id, *data),
        )

        return msg_id

    async def _recv_msg(self, pool_id: str, msg_id: str, expect: ExecutionManagerProtocolKeys, close_msg_queue: bool) -> tuple[str, Any]:
        # Get the queue for this message and the recv task
        msg_queue = self._msgs[pool_id][msg_id]
        msg_recv_task = self._msg_recv_tasks.get(pool_id)

        # Create a task to wait for the message
        get_task = asyncio.create_task(msg_queue.get())

        # Wait for either the message or the recv task to complete (crash)
        if msg_recv_task is not None:
            done, pending = await asyncio.wait(
                [get_task, msg_recv_task],
                return_when=asyncio.FIRST_COMPLETED
            )

            # If the recv task completed (crashed), cancel the get and propagate exception
            if msg_recv_task in done:
                get_task.cancel()
                try:
                    await get_task
                except asyncio.CancelledError:
                    pass
                if close_msg_queue:
                    del self._msgs[pool_id][msg_id]
                exc = msg_recv_task.exception()
                if exc is not None:
                    raise exc
                # Recv task ended without exception - shouldn't happen in normal operation
                raise RuntimeError("Message receiver task ended unexpectedly")

            # Otherwise, get the message result
            msg = get_task.result()
        else:
            msg = await get_task

        if close_msg_queue:
            del self._msgs[pool_id][msg_id]
            self._msg_worker_map.get(pool_id, {}).pop(msg_id, None)

        # Check for pool-level error routed from _msg_recv_task_func
        if msg.key in POOL_UP_ERROR_KEYS:
            _check_error_and_raise(msg)

        if msg.key != expect.value:
            raise ValueError(f"Expected message key '{expect.value}', got '{msg.key}'.")

        return msg

    async def run(
        self,
        pool_id: str,
        worker_id: str,
        func_import_path_or_key: str,
        func_args,
        func_kwargs,
    ) -> JobResult:
        """
        Run a function on a specific worker and wait for the result.

        Sends a `RUN` request to the target worker and waits for the single
        `UP_RUN_RESPONSE` terminal event, which carries the result and timing
        metadata. Worker crashes are surfaced as exceptions on the affected
        job without disturbing the rest of the pool.

        Args:
            pool_id: The pool to run on.
            worker_id: The specific worker (within the pool) to run on.
            func_import_path_or_key: Either an importable dotted path
                (e.g. `"my_pkg.my_func"`), or a key previously registered via
                `send_function()` / `send_function_to_pool()`.
            func_args: Positional arguments tuple.
            func_kwargs: Keyword arguments dict.

        Returns:
            A `JobResult` with submitted/started/completed timestamps, the
            return value, pool/worker IDs, and a flag indicating whether the
            result was string-converted (for non-serializable returns from
            multiprocess/remote pools).

        Raises:
            Whatever the user function raises, propagated to the caller.
        """
        pool = self._pools[pool_id]

        run_id = str(uuid.uuid4())
        timestamp_utc_submitted = get_timestamp_utc()

        # Update round-robin and job tracking BEFORE the first await,
        # so concurrent tasks see the updated allocation state immediately.
        job_info = SubmittedJobInfo(
            run_id=run_id,
            timestamp_utc_submitted=timestamp_utc_submitted,
            timestamp_utc_started=None,
            func_import_path_or_key=func_import_path_or_key,
            pool_id=pool_id,
            worker_id=worker_id,
        )
        self._worker_jobs[(pool_id, worker_id)].append(job_info)

        msg_id = None
        try:
            msg_id = await self._send_msg(
                pool_id=pool_id,
                worker_id=worker_id,
                key=ExecutionManagerProtocolKeys.RUN.value,
                data=(func_import_path_or_key, run_id, func_args, func_kwargs),
            )

            # Wait for UP_RUN_RESPONSE (single response containing all timestamps)
            msg = await self._recv_msg(pool_id, msg_id, expect=ExecutionManagerProtocolKeys.UP_RUN_RESPONSE, close_msg_queue=True)
            msg_id = None  # Already cleaned up by close_msg_queue=True

            self._worker_jobs[(pool_id, worker_id)].remove(job_info)

            timestamp_utc_started, timestamp_utc_completed, converted_to_str, _res = msg.data
            job_info.timestamp_utc_started = timestamp_utc_started
            if isinstance(_res, Exception):
                raise _res
            return JobResult(
                timestamp_utc_submitted=job_info.timestamp_utc_submitted,
                timestamp_utc_started=timestamp_utc_started,
                timestamp_utc_completed=timestamp_utc_completed,
                func_import_path_or_key=job_info.func_import_path_or_key,
                pool_id=job_info.pool_id,
                worker_id=job_info.worker_id,
                converted_to_str=converted_to_str,
                result=_res,
            )
        finally:
            # Clean up leaked state on cancellation/exception
            try:
                self._worker_jobs[(pool_id, worker_id)].remove(job_info)
            except ValueError:
                pass  # Already removed on the success path
            if msg_id is not None and msg_id in self._msgs.get(pool_id, {}):
                del self._msgs[pool_id][msg_id]
                self._msg_worker_map.get(pool_id, {}).pop(msg_id, None)

    async def run_allocate(
        self,
        pool_worker_ids: list[str | tuple[str, str]],
        allocation_method: RunAllocationMethod,
        func_import_path_or_key: str,
        func_args,
        func_kwargs,
    ) -> JobResult:
        """
        Pick a worker from the candidate list using `allocation_method`, then run.

        Args:
            pool_worker_ids: Candidate workers. Each entry is either a pool ID
                (which expands to all workers in that pool) or a `(pool_id,
                worker_id)` tuple targeting a specific worker.
            allocation_method: `ROUND_ROBIN` (rotates across candidates),
                `RANDOM` (uniform pick), or `LEAST_BUSY` (worker with fewest
                in-flight jobs; ties broken by round-robin).
            func_import_path_or_key: See `run()`.
            func_args: Positional arguments tuple.
            func_kwargs: Keyword arguments dict.

        Returns:
            A `JobResult` from the selected worker.

        Raises:
            ValueError: If the candidate list is empty.
        """
        worker_ids: list[tuple[str, int]] = []
        # Convert pool_worker_ids to a list of (pool_id, worker_id) tuples
        for _id in pool_worker_ids:
            if isinstance(_id, str):
                pool = self._pools[_id]
                for worker_id in range(pool.num_workers):
                    worker_ids.append((_id, worker_id))
            else:
                pool_id, worker_id = _id
                worker_ids.append((pool_id, worker_id))

        if not worker_ids:
            raise ValueError("No workers available for allocation.")

        # Select worker based on allocation method
        if allocation_method == RunAllocationMethod.ROUND_ROBIN:
            idx = self._round_robin_counter % len(worker_ids)
            pool_id, worker_id = worker_ids[idx]
            self._round_robin_counter += 1

        elif allocation_method == RunAllocationMethod.RANDOM:
            pool_id, worker_id = random.choice(worker_ids)

        elif allocation_method == RunAllocationMethod.LEAST_BUSY:
            # Choose the worker with the fewest active jobs (jobs that have been submitted
            # but not yet completed). A worker with no recorded jobs is preferred.
            def active_job_count(pool_worker: tuple[str, str]) -> int:
                key = pool_worker
                jobs = self._worker_jobs.get(key, [])
                # Active = submitted but not yet completed; here we treat presence in the
                # list as active, and completion will remove the job from this structure.
                return len(jobs)

            pool_id, worker_id = min(worker_ids, key=active_job_count)

        else:
            raise ValueError(f"Unknown allocation method: '{allocation_method}'.")

        return await self.run(
            pool_id=pool_id,
            worker_id=worker_id,
            func_import_path_or_key=func_import_path_or_key,
            func_args=func_args,
            func_kwargs=func_kwargs,
        )

    async def send_function(self, pool_id: str, worker_id: str, func_key: str, func: Callable[..., Any]|Callable[..., Awaitable[Any]]) -> None:
        """
        Send a function to a worker in a pool, such that it can be run using the given key using `ExecutionManager.run`.

        Args:
            pool_id: The ID of the pool to send the function to.
            worker_id: The ID of the worker to send the function to.
            func_key: The key of the function to send. 
            func: The function to send.
        """
        # If the pool is a multiprocess pool or remote pool, the function needs to be pickleable.
        pool = self._pools[pool_id]
        if isinstance(pool, (MultiprocessPool, RemotePoolClient)):
            try:
                pickle.dumps(func)
            except pickle.PicklingError:
                raise ValueError(f"Function {func} (key = '{func_key}') is not pickleable. Cannot send to worker in pool '{pool_id}'.")

        msg_id = await self._send_msg(
            pool_id=pool_id,
            worker_id=worker_id,
            key=ExecutionManagerProtocolKeys.SEND_FUNCTION.value,
            data=(func_key, func),
        )
        await self._recv_msg(pool_id, msg_id, expect=ExecutionManagerProtocolKeys.UP_SEND_FUNCTION_RESPONSE, close_msg_queue=True)

    async def send_function_to_pool(self, pool_id: str, func_key: str, func: Callable[..., Any]|Callable[..., Awaitable[Any]]) -> None:
        """
        Send a function to all workers in a pool.

        Args:
            pool_id: The ID of the pool to send the function to.
            func_key: The key of the function to send.
            func: The function to send.
        """
        tasks = [asyncio.create_task(self.send_function(pool_id, worker_id, func_key, func)) for worker_id in range(self._pools[pool_id].num_workers)]
        await asyncio.gather(*tasks)

    async def close(self):
        """Close the execution manager and all its pools."""
        # Cancel message receiver tasks FIRST to prevent them from trying to
        # recv from closed pools (which would raise PoolNotStarted)
        errors = []
        for task in self._msg_recv_tasks.values():
            task.cancel()
        for task in self._msg_recv_tasks.values():
            try:
                await task
            except asyncio.CancelledError:
                pass
            except Exception as e:
                errors.append(e)

        # Now close the pools
        for pool in self._pools.values():
            await pool.close()

        # Stop the shared event loop
        if self._shared_loop is not None:
            self._shared_loop.call_soon_threadsafe(self._shared_loop.stop)
            if self._shared_loop_thread is not None:
                self._shared_loop_thread.join(timeout=5.0)
            self._shared_loop.close()
            self._shared_loop = None
            self._shared_loop_thread = None

        self._started = False

        # Propagate any errors from the recv tasks
        if errors:
            raise errors[0]

    @property
    def pools(self) -> list[tuple[str, type[PoolType]]]:
        """Get list of pool IDs."""
        return [(k, type(v)) for k, v in self._pools.items()]

    def get_pool(self, pool_id: str) -> PoolType:
        """Get a pool instance by ID.

        Args:
            pool_id: The ID of the pool.

        Returns:
            The pool instance.

        Raises:
            KeyError: If the pool ID is not found.
        """
        if pool_id not in self._pools:
            raise KeyError(f"Pool '{pool_id}' not found")
        return self._pools[pool_id]

    def get_num_workers(self, pool_id: str) -> int:
        """Get the number of workers in a pool."""
        return self._pools[pool_id].num_workers

    def get_worker_ids(self, pool_id: str) -> list[str]:
        """Get the list of worker IDs for a pool."""
        return [f"{pool_id}_{i}" for i in range(self._pools[pool_id].num_workers)]

    def get_worker_jobs(self, pool_id: str, worker_id: int) -> list[SubmittedJobInfo]:
        """Get the list of currently submitted jobs for a worker."""
        return list(self._worker_jobs.get((pool_id, worker_id), []))

    @property
    def started(self) -> bool:
        """Check if the execution manager has been started."""
        return self._started

    def get_process_ids(self, pool_id: str) -> list[int]:
        """Get all process IDs for a MultiprocessPool.

        Args:
            pool_id: The ID of the pool.

        Returns:
            List of process indices (0 to num_processes-1).

        Raises:
            ValueError: If the pool is not a MultiprocessPool.
        """
        pool = self._pools[pool_id]
        if not isinstance(pool, MultiprocessPool):
            raise ValueError(f"Pool '{pool_id}' is not a MultiprocessPool (got {type(pool).__name__})")
        return list(range(pool.num_processes))

    async def flush_pool_stdout(
        self, pool_id: str, process_idx: int, timeout: float | None = None
    ) -> list[tuple[datetime, bool, str]]:
        """Flush and retrieve stdout/stderr buffer from a specific process in a MultiprocessPool.

        Args:
            pool_id: The ID of the pool.
            process_idx: Index of the process (0 to num_processes-1).
            timeout: Maximum time to wait for response in seconds.

        Returns:
            List of (timestamp, is_stdout, text) tuples.
            is_stdout is True for stdout, False for stderr.

        Raises:
            ValueError: If the pool is not a MultiprocessPool.
            PoolNotStarted: If the pool is not running.
        """
        pool = self._pools[pool_id]
        if not isinstance(pool, MultiprocessPool):
            raise ValueError(f"Pool '{pool_id}' is not a MultiprocessPool (got {type(pool).__name__})")
        return await pool.flush_stdout(process_idx, timeout=timeout)

    async def flush_all_pool_stdout(
        self, pool_id: str, timeout: float | None = None
    ) -> dict[int, list[tuple[datetime, bool, str]]]:
        """Flush and retrieve stdout/stderr buffers from all processes in a MultiprocessPool.

        Args:
            pool_id: The ID of the pool.
            timeout: Maximum time to wait for each process response.

        Returns:
            Dict mapping process_idx to list of (timestamp, is_stdout, text) tuples.

        Raises:
            ValueError: If the pool is not a MultiprocessPool.
            PoolNotStarted: If the pool is not running.
        """
        pool = self._pools[pool_id]
        if not isinstance(pool, MultiprocessPool):
            raise ValueError(f"Pool '{pool_id}' is not a MultiprocessPool (got {type(pool).__name__})")
        return await pool.flush_all_stdout(timeout=timeout)

    async def __aenter__(self) -> "ExecutionManager":
        """Context manager entry - starts the manager."""
        await self.start()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Context manager exit - closes the manager."""
        await self.close()
