# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/10_cli/test_cli_graph.pct.py

__all__ = ['runner', 'test_add_edge_bad_format', 'test_add_edge_basic', 'test_add_edge_dependency', 'test_add_edge_fan_out_warning', 'test_add_edge_missing_node', 'test_add_node_auto_position', 'test_add_node_custom_position', 'test_add_node_duplicate_error', 'test_add_node_factory', 'test_add_node_json_stdin', 'test_add_node_raw_ports', 'test_edit_node_merge', 'test_edit_node_not_found', 'test_edit_node_ports', 'test_edit_node_rename', 'test_remove_edge_basic', 'test_remove_edge_not_found', 'test_remove_node_not_found', 'test_remove_node_with_edges', 'test_validate_fan_out_suggestion']

# %% pts/tests/10_cli/test_cli_graph.pct.py 2
import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from netrun.cli._app import app

# %% pts/tests/10_cli/test_cli_graph.pct.py 3
runner = CliRunner()


def _make_config(tmp_path: Path, data: dict) -> str:
    """Write a temp .netrun.json and return its path as a string."""
    p = tmp_path / "test.netrun.json"
    p.write_text(json.dumps(data, indent=2))
    return str(p)


def _base_config() -> dict:
    """Minimal config with two nodes and one edge."""
    return {
        "graph": {
            "nodes": [
                {
                    "name": "A",
                    "in_ports": {"in": {}},
                    "out_ports": {"out": {}},
                    "extra": {"ui": {"position": {"x": 100, "y": 200}}},
                },
                {
                    "name": "B",
                    "in_ports": {"in": {}},
                    "out_ports": {"out": {}},
                    "extra": {"ui": {"position": {"x": 400, "y": 200}}},
                },
            ],
            "edges": [
                {"source_str": "A.out", "target_str": "B.in"},
            ],
        }
    }

# %% pts/tests/10_cli/test_cli_graph.pct.py 5
def test_add_node_factory(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, [
        "add-node", "C", "-c", cfg,
        "--factory", "netrun.node_factories.from_function",
        "--factory-arg", "func=my_module.my_func",
        "--no-validate",
    ])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert node["name"] == "C"
    assert node["factory"] == "netrun.node_factories.from_function"
    assert node["factory_args"]["func"] == "my_module.my_func"
    # Check it was written
    written = json.loads(Path(cfg).read_text())
    names = [n["name"] for n in written["graph"]["nodes"]]
    assert "C" in names


def test_add_node_raw_ports(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, [
        "add-node", "C", "-c", cfg,
        "--in-ports", "x,y",
        "--out-ports", "result",
        "--no-validate",
    ])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert "x" in node["in_ports"]
    assert "y" in node["in_ports"]
    assert "result" in node["out_ports"]


def test_add_node_json_stdin(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    node_json = json.dumps({"in_ports": {"data": {}}, "out_ports": {"result": {}}, "factory": "some.factory"})
    result = runner.invoke(app, [
        "add-node", "C", "-c", cfg, "--json", "--no-validate",
    ], input=node_json)
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert node["name"] == "C"
    assert node["factory"] == "some.factory"
    assert "data" in node["in_ports"]


def test_add_node_duplicate_error(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["add-node", "A", "-c", cfg, "--no-validate"])
    assert result.exit_code == 1
    assert "already exists" in result.output


def test_add_node_custom_position(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, [
        "add-node", "C", "-c", cfg,
        "--position", "500,300",
        "--no-validate",
    ])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert node["extra"]["ui"]["position"]["x"] == 500.0
    assert node["extra"]["ui"]["position"]["y"] == 300.0


def test_add_node_auto_position(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["add-node", "C", "-c", cfg, "--no-validate"])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    # max x is 400, so auto should be 700; avg y is 200
    assert node["extra"]["ui"]["position"]["x"] == 700.0
    assert node["extra"]["ui"]["position"]["y"] == 200.0

# %% pts/tests/10_cli/test_cli_graph.pct.py 7
def test_remove_node_with_edges(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["remove-node", "A", "-c", cfg, "--no-validate"])
    assert result.exit_code == 0, result.output
    out = json.loads(result.stdout)
    assert out["removed"] == "A"
    assert out["edges_removed"] == 1
    # Verify config
    written = json.loads(Path(cfg).read_text())
    names = [n["name"] for n in written["graph"]["nodes"]]
    assert "A" not in names
    assert len(written["graph"]["edges"]) == 0


def test_remove_node_not_found(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["remove-node", "Z", "-c", cfg, "--no-validate"])
    assert result.exit_code == 1
    assert "not found" in result.output

# %% pts/tests/10_cli/test_cli_graph.pct.py 9
def test_edit_node_rename(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["edit-node", "A", "-c", cfg, "--rename", "Alpha", "--no-validate"])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert node["name"] == "Alpha"
    # Verify edge refs updated
    written = json.loads(Path(cfg).read_text())
    edge = written["graph"]["edges"][0]
    assert edge["source_str"] == "Alpha.out"


def test_edit_node_ports(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, [
        "edit-node", "A", "-c", cfg,
        "--add-in-port", "extra_in",
        "--add-out-port", "extra_out",
        "--remove-in-port", "in",
        "--no-validate",
    ])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert "extra_in" in node["in_ports"]
    assert "extra_out" in node["out_ports"]
    assert "in" not in node["in_ports"]


def test_edit_node_merge(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    merge_json = json.dumps({"execution_config": {"pools": ["main"]}})
    result = runner.invoke(app, [
        "edit-node", "A", "-c", cfg,
        "--merge", merge_json,
        "--no-validate",
    ])
    assert result.exit_code == 0, result.output
    node = json.loads(result.stdout)
    assert node["execution_config"]["pools"] == ["main"]
    # Original fields preserved
    assert node["name"] == "A"
    assert "out" in node["out_ports"]


def test_edit_node_not_found(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["edit-node", "Z", "-c", cfg, "--rename", "ZZ", "--no-validate"])
    assert result.exit_code == 1
    assert "not found" in result.output

# %% pts/tests/10_cli/test_cli_graph.pct.py 11
def test_add_edge_basic(tmp_path):
    data = _base_config()
    data["graph"]["edges"] = []  # Start with no edges
    cfg = _make_config(tmp_path, data)
    result = runner.invoke(app, ["add-edge", "A.out", "B.in", "-c", cfg, "--no-validate"])
    assert result.exit_code == 0, result.output
    edge = json.loads(result.stdout)
    assert edge["source_str"] == "A.out"
    assert edge["target_str"] == "B.in"
    # Verify written
    written = json.loads(Path(cfg).read_text())
    assert len(written["graph"]["edges"]) == 1


def test_add_edge_dependency(tmp_path):
    data = _base_config()
    data["graph"]["edges"] = []
    cfg = _make_config(tmp_path, data)
    result = runner.invoke(app, ["add-edge", "A.out", "B.in", "-c", cfg, "--dependency", "--no-validate"])
    assert result.exit_code == 0, result.output
    edge = json.loads(result.stdout)
    assert edge["dependency"] is True


def test_add_edge_fan_out_warning(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    # A.out already has an edge; adding another should warn
    # First add a third node
    runner.invoke(app, ["add-node", "C", "-c", cfg, "--in-ports", "in", "--no-validate"])
    result = runner.invoke(app, ["add-edge", "A.out", "C.in", "-c", cfg, "--no-validate"])
    assert result.exit_code == 0, result.output
    assert "fan-out" in result.output.lower() or "Fan-out" in result.output


def test_add_edge_missing_node(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["add-edge", "Z.out", "B.in", "-c", cfg, "--no-validate"])
    assert result.exit_code == 1
    assert "not found" in result.output


def test_add_edge_bad_format(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["add-edge", "Aout", "Bin", "-c", cfg, "--no-validate"])
    assert result.exit_code == 1
    assert "Node.port" in result.output

# %% pts/tests/10_cli/test_cli_graph.pct.py 13
def test_remove_edge_basic(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["remove-edge", "A.out", "B.in", "-c", cfg, "--no-validate"])
    assert result.exit_code == 0, result.output
    out = json.loads(result.stdout)
    assert out["removed_source"] == "A.out"
    # Verify
    written = json.loads(Path(cfg).read_text())
    assert len(written["graph"]["edges"]) == 0


def test_remove_edge_not_found(tmp_path):
    cfg = _make_config(tmp_path, _base_config())
    result = runner.invoke(app, ["remove-edge", "X.out", "Y.in", "-c", cfg, "--no-validate"])
    assert result.exit_code == 1
    assert "not found" in result.output

# %% pts/tests/10_cli/test_cli_graph.pct.py 15
def test_validate_fan_out_suggestion():
    from netrun.net.config._graph import GraphConfig
    from netrun.net.config._nodes import NodeConfig, PortConfig, EdgeConfig

    config = GraphConfig(
        nodes=[
            NodeConfig(name="A", out_ports={"out": PortConfig()}),
            NodeConfig(name="B", in_ports={"in": PortConfig()}),
            NodeConfig(name="C", in_ports={"in": PortConfig()}),
        ],
        edges=[
            EdgeConfig(source_str="A.out", target_str="B.in"),
            EdgeConfig(source_str="A.out", target_str="C.in"),
        ],
    )
    errors = config.validate()
    fan_out_errors = [e for e in errors if e.type == "fan_out"]
    assert len(fan_out_errors) > 0
    assert "netrun.node_factories.broadcast" in fan_out_errors[0].msg
