# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/netrun/05_net/01_net.ipynb

__all__ = ['Net', 'NodeExecutionContext', 'NodeFailureContext']

# %% nbs/netrun/05_net/01_net.ipynb 2
import asyncio

import netrun_sim
from ..pool.thread import ThreadPool
from ..pool.multiprocess import MultiprocessPool
from ..pool.aio import SingleWorkerPool
from ..pool.remote import RemotePoolClient
from ..net.config import NetConfig
from ..execution_manager import PoolType

# %% nbs/netrun/05_net/01_net.ipynb 3
class NodeExecutionContext:
    pass

class NodeFailureContext:
    pass

# %% nbs/netrun/05_net/01_net.ipynb 4
class Net:
    def __init__(self, config: NetConfig):
        self._config: NetConfig = config
        self._graph: netrun_sim.Graph = self.config.graph.get_graph()
        self._netsim = netrun_sim.NetSim(self._graph)
        self._started: bool = False

        _exec_manager_config = {}
        for pool_name, pool_config in self.config.pools.items():
            match pool_config.spec.type:
                case "main": pool_type = SingleWorkerPool
                case "thread": pool_type = ThreadPool
                case "multiprocess": pool_type = MultiprocessPool
                case "remote": pool_type = RemotePoolClient
                case _: raise ValueError(f"Invalid pool type: {pool_config.spec.type}")
            _init_kwargs = pool_config.spec.model_dump()
            _init_kwargs.pop("type")
            _exec_manager_config[pool_name] = (pool_type, _init_kwargs)
        self._execution_manager = ExecutionManager(_exec_manager_config)

    @property
    def config(self) -> NetConfig:
        return self._config

    @property
    def graph(self) -> netrun_sim.Graph:
        return self._graph

    @property
    def pools(self) -> list[tuple[str, type[PoolType]]]:
        return self._execution_manager.pools

    @property
    def started(self) -> bool:
        return self._started

    def start_pools(self):
        """
        Can be used before `Net.start`, to initialise the pools before starting the Net itself.
        """
        if self._execution_manager.started:
            raise RuntimeError("Execution manager already started")
        self._execution_manager.start()

    def start(self):
        if self._started:
            raise RuntimeError("Net already started")
        if not self.start_pools():
            self.start_pools()
        self._execution_manager.start()

    def stop(self):
        self._execution_manager.stop()

    # send_packet_to_input_port
    # execute_epoch

    async def async_run_step(self):
        self.netsim

    def run_step(self):
        asyncio.run(self.async_run_step())
