[project]
name = "thread-and-process-pools"
version = "0.1.0"
description = "Thread and process pool examples for netrun"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "netrun",
    "netrun-ui",
]

[tool.uv.sources]
netrun = { path = "../../netrun", editable = true }
netrun-ui = { path = "../../netrun-ui", editable = true }
