[project]
name = "basic-net-project"
version = "0.1.0"
description = "A basic example of using netrun"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "netrun",
    "netrun-ui",
]

[tool.uv.sources]
netrun = { path = "../../netrun", editable = true }
netrun-ui = { path = "../../netrun-ui", editable = true }
