# AUTOGENERATED! DO NOT EDIT! File to edit: pts/netrun/04_pool/04_aio.pct.py

__all__ = ['AsyncWorkerFn', 'SingleWorkerPool']

# %% pts/netrun/04_pool/04_aio.pct.py 3
import asyncio
import logging
from typing import Any
from collections.abc import Callable, Awaitable

from ..rpc.base import ChannelClosed, RecvTimeout
from ..rpc.aio import (
    AsyncChannel,
    create_async_channel_pair,
)
from ..pool.base import (
    BasePool,
    WorkerId,
    WorkerMessage,
    PoolNotStarted,
    PoolAlreadyStarted,
    POOL_UP_ERROR_EXCEPTION,
    POOL_UP_ERROR_CRASHED,
    _check_error_and_raise,
)

# %% pts/netrun/04_pool/04_aio.pct.py 5
AsyncWorkerFn = Callable[[AsyncChannel, WorkerId], Awaitable[None]]
"""Type for async worker functions: async def worker(channel, worker_id) -> None"""

# %% pts/netrun/04_pool/04_aio.pct.py 7
class SingleWorkerPool(BasePool):
    """A pool with a single async worker coroutine.

    Designed for the main thread of netrun where the "worker" is
    an async coroutine running in the same event loop. Unlike ThreadPool
    or MultiprocessPool, this does not spawn threads or processes.
    """

    def __init__(self, worker_fn: AsyncWorkerFn, **kwargs):
        """Create a single-worker async pool.

        Args:
            worker_fn: Async function to run as the worker.
                       Signature: async def worker(channel: AsyncChannel, worker_id: int) -> None
        """
        super().__init__(num_workers=1, **kwargs)
        self._worker_fn = worker_fn
        self._channel: AsyncChannel | None = None
        self._worker_channel: AsyncChannel | None = None
        self._worker_task: asyncio.Task | None = None

    async def _do_start(self) -> None:
        self._channel, self._worker_channel = create_async_channel_pair()
        self._worker_task = asyncio.create_task(self._run_worker())

    async def _run_worker(self) -> None:
        """Run the worker function."""
        try:
            await self._worker_fn(self._worker_channel, 0)
        except ChannelClosed:
            pass
        except Exception as e:
            try:
                await self._worker_channel.send(POOL_UP_ERROR_EXCEPTION, e)
            except Exception:
                pass

    async def _do_close(self, timeout: float | None = None) -> None:
        # Close channel to signal worker to stop
        if self._channel:
            await self._channel.close()

        # Wait for worker task to finish
        if self._worker_task and not self._worker_task.done():
            if timeout is not None:
                try:
                    await asyncio.wait_for(self._worker_task, timeout=timeout)
                except TimeoutError:
                    self._worker_task.cancel()
                    try:
                        await self._worker_task
                    except asyncio.CancelledError:
                        pass
            else:
                try:
                    await self._worker_task
                except asyncio.CancelledError:
                    pass

        self._channel = None
        self._worker_channel = None
        self._worker_task = None

    def _create_recv_loops(self) -> list:
        async def recv_loop():
            try:
                while self._running:
                    key, data = await self._channel.recv()
                    await self._recv_queue.put(WorkerMessage(worker_id=0, key=key, data=data))
            except (ChannelClosed, asyncio.CancelledError):
                pass
            except Exception as e:
                logging.getLogger("netrun.pool").error(
                    f"recv_loop for worker 0 crashed: {e}", exc_info=True
                )
                await self._recv_queue.put(WorkerMessage(
                    worker_id=0, key=POOL_UP_ERROR_CRASHED,
                    data={"reason": f"recv_loop exception: {e}"},
                ))
        return [recv_loop()]

    async def _check_worker_health(self) -> None:
        if self._worker_task and self._worker_task.done() and self._running:
            await self._recv_queue.put(WorkerMessage(
                worker_id=0, key=POOL_UP_ERROR_CRASHED,
                data={"reason": "Worker task ended unexpectedly"},
            ))

    async def _try_recv_direct(self) -> WorkerMessage | None:
        """Read directly from channel (when recv tasks aren't running)."""
        result = await self._channel.try_recv()
        if result is not None:
            key, data = result
            return WorkerMessage(worker_id=0, key=key, data=data)
        return None

    async def send(self, worker_id: WorkerId, key: str, data: Any) -> None:
        if not self._running:
            raise PoolNotStarted("Pool has not been started")
        if worker_id != 0:
            raise ValueError(f"worker_id must be 0, got {worker_id}")
        await self._channel.send(key, data)

    async def broadcast(self, key: str, data: Any) -> None:
        if not self._running:
            raise PoolNotStarted("Pool has not been started")
        await self._channel.send(key, data)
