# Simple netrun configuration example

[meta]
description = "A simple two-node flow"

[[graph.nodes]]
name = "Input"

[graph.nodes.out_ports.out]
port_type = "any"

[graph.nodes.meta.ui]
id = "node-input"
label = "Input"
position = {x = 150, y = 150}

[[graph.nodes]]
name = "Output"

[graph.nodes.in_ports.in]
port_type = "any"

[graph.nodes.meta.ui]
id = "node-output"
label = "Output"
position = {x = 450, y = 150}

[[graph.edges]]
source_str = "Input.out"
target_str = "Output.in"
