/**
 * Salvo condition types.
 *
 * Re-exports from netrun-ui-vis for backwards compatibility.
 */
export {
	type MaxSalvosInfinite,
	type MaxSalvosFinite,
	type MaxSalvosConfig,
	type PortStateEmpty,
	type PortStateFull,
	type PortStateNonEmpty,
	type PortStateNonFull,
	type PortStateEquals,
	type PortStateLessThan,
	type PortStateGreaterThan,
	type PortStateEqualsOrLessThan,
	type PortStateEqualsOrGreaterThan,
	type PortStateConfig,
	type PacketCountAll,
	type PacketCountN,
	type PacketCountConfig,
	type TermTrue,
	type TermFalse,
	type TermPort,
	type TermAnd,
	type TermOr,
	type TermNot,
	type SalvoConditionTermConfig,
	type SalvoConditionConfig,
	type SalvoConditionPreset,
	type SalvoConditionUIState,
	createDefaultMaxSalvos,
	createDefaultPacketCount,
	createTermTrue,
	createTermFalse,
	createTermPortNonEmpty,
	createTermAnd,
	createTermOr,
	createTermNot,
	createAllPortsReadyTerm,
	createDefaultSalvoCondition,
	createDefaultUIState,
} from 'netrun-ui-vis';
