# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tests/03_pool/test_exceptions_remote.ipynb

__all__ = ['test_broadcast_before_create_pool', 'test_connection_error_no_server', 'test_exception_hierarchy', 'test_recv_before_create_pool', 'test_recv_timeout', 'test_recv_timeout_preserves_client', 'test_send_before_create_pool', 'test_send_invalid_worker_id_negative', 'test_send_invalid_worker_id_too_large', 'test_try_recv_before_create_pool', 'test_try_recv_returns_none', 'test_unknown_worker_error', 'test_worker_crashed_structure', 'test_worker_exception', 'test_worker_exception_structure']

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 2
import pytest
import time
from netrun.rpc.base import RecvTimeout
from netrun.pool.base import (
    PoolError,
    PoolNotStarted,
    WorkerException,
    WorkerCrashed,
)
from netrun.pool.remote import RemotePoolServer, RemotePoolClient

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 4
from ..pool.workers import echo_worker, compute_worker, raising_worker

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 7
@pytest.mark.asyncio
async def test_send_before_create_pool():
    """RemotePoolClient.send() raises PoolNotStarted before create_pool()."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29901):
        async with RemotePoolClient("ws://127.0.0.1:29901") as client:
            # Connected but no pool created yet
            with pytest.raises(PoolNotStarted) as exc_info:
                await client.send(0, "hello", "world")

            assert "not created" in str(exc_info.value).lower()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 9
@pytest.mark.asyncio
async def test_recv_before_create_pool():
    """RemotePoolClient.recv() raises PoolNotStarted before create_pool()."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29902):
        async with RemotePoolClient("ws://127.0.0.1:29902") as client:
            with pytest.raises(PoolNotStarted):
                await client.recv(timeout=0.1)

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 11
@pytest.mark.asyncio
async def test_try_recv_before_create_pool():
    """RemotePoolClient.try_recv() raises PoolNotStarted before create_pool()."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29903):
        async with RemotePoolClient("ws://127.0.0.1:29903") as client:
            with pytest.raises(PoolNotStarted):
                await client.try_recv()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 13
@pytest.mark.asyncio
async def test_broadcast_before_create_pool():
    """RemotePoolClient.broadcast() raises PoolNotStarted before create_pool()."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29904):
        async with RemotePoolClient("ws://127.0.0.1:29904") as client:
            with pytest.raises(PoolNotStarted):
                await client.broadcast("hello", "world")

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 16
@pytest.mark.asyncio
async def test_unknown_worker_error():
    """create_pool() raises PoolError for unknown worker name."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29905):
        async with RemotePoolClient("ws://127.0.0.1:29905") as client:
            with pytest.raises(PoolError) as exc_info:
                await client.create_pool(
                    worker_name="nonexistent",
                    num_processes=1,
                )

            assert "unknown worker" in str(exc_info.value).lower()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 19
@pytest.mark.asyncio
async def test_recv_timeout():
    """RemotePoolClient.recv() raises RecvTimeout when timeout expires."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29906):
        async with RemotePoolClient("ws://127.0.0.1:29906") as client:
            await client.create_pool(worker_name="echo", num_processes=1)

            start = time.time()
            with pytest.raises(RecvTimeout) as exc_info:
                await client.recv(timeout=0.1)
            elapsed = time.time() - start

            assert elapsed >= 0.1
            assert elapsed < 0.5
            assert "timed out" in str(exc_info.value).lower()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 21
@pytest.mark.asyncio
async def test_recv_timeout_preserves_client():
    """After RecvTimeout, the client is still usable."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29907):
        async with RemotePoolClient("ws://127.0.0.1:29907") as client:
            await client.create_pool(worker_name="echo", num_processes=1)

            # First recv times out
            with pytest.raises(RecvTimeout):
                await client.recv(timeout=0.05)

            # Client should still be running
            assert client.is_running

            # Can still send and receive
            await client.send(0, "hello", "world")
            msg = await client.recv(timeout=5.0)
            assert msg.key == "echo:hello"
            assert msg.data["data"] == "world"

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 24
@pytest.mark.asyncio
async def test_try_recv_returns_none():
    """RemotePoolClient.try_recv() returns None, never raises RecvTimeout."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29908):
        async with RemotePoolClient("ws://127.0.0.1:29908") as client:
            await client.create_pool(worker_name="echo", num_processes=1)

            result = await client.try_recv()
            assert result is None

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 27
@pytest.mark.asyncio
async def test_worker_exception():
    """WorkerException is raised when remote worker raises exception."""
    server = RemotePoolServer()
    server.register_worker("raising", raising_worker)

    async with server.serve_background("127.0.0.1", 29909):
        async with RemotePoolClient("ws://127.0.0.1:29909") as client:
            await client.create_pool(worker_name="raising", num_processes=1)

            await client.send(0, "raise", "test error")

            with pytest.raises(WorkerException) as exc_info:
                await client.recv(timeout=5.0)

            exc = exc_info.value
            assert exc.worker_id == 0
            # Remote exceptions come as dict
            assert "ValueError" in str(exc)

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 29
def test_worker_exception_structure():
    """WorkerException has the expected structure."""
    error_dict = {
        "type": "ValueError",
        "message": "Test error",
    }
    exc = WorkerException(0, error_dict)

    assert exc.worker_id == 0
    assert "ValueError" in str(exc)
    assert "Test error" in str(exc)

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 32
def test_worker_crashed_structure():
    """WorkerCrashed has the expected structure."""
    details = {"exit_code": -9, "reason": "Process killed"}
    exc = WorkerCrashed(2, details)

    assert exc.worker_id == 2
    assert exc.details == details
    assert "Worker 2" in str(exc)
    assert "crashed" in str(exc).lower()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 35
@pytest.mark.asyncio
async def test_send_invalid_worker_id_negative():
    """send() raises ValueError for negative worker_id."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29910):
        async with RemotePoolClient("ws://127.0.0.1:29910") as client:
            await client.create_pool(worker_name="echo", num_processes=2)

            with pytest.raises(ValueError) as exc_info:
                await client.send(-1, "hello", "world")

            assert "out of range" in str(exc_info.value)

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 37
@pytest.mark.asyncio
async def test_send_invalid_worker_id_too_large():
    """send() raises ValueError for worker_id >= num_workers."""
    server = RemotePoolServer()
    server.register_worker("echo", echo_worker)

    async with server.serve_background("127.0.0.1", 29911):
        async with RemotePoolClient("ws://127.0.0.1:29911") as client:
            await client.create_pool(
                worker_name="echo",
                num_processes=2,
                threads_per_process=2,
            )
            # Total workers = 4, valid IDs are 0, 1, 2, 3

            with pytest.raises(ValueError) as exc_info:
                await client.send(4, "hello", "world")

            assert "out of range" in str(exc_info.value)

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 40
@pytest.mark.asyncio
async def test_connection_error_no_server():
    """connect() raises error when server is not available."""
    client = RemotePoolClient("ws://127.0.0.1:29999")  # No server

    with pytest.raises(Exception):  # May be ConnectionError or OSError
        await client.connect()

# %% nbs/tests/03_pool/test_exceptions_remote.ipynb 43
def test_exception_hierarchy():
    """Verify exception hierarchy is correct."""
    assert issubclass(PoolNotStarted, PoolError)
    assert issubclass(WorkerException, PoolError)
    assert issubclass(WorkerCrashed, PoolError)
    assert issubclass(PoolError, Exception)

    # RecvTimeout is from RPC layer, not PoolError
    assert not issubclass(RecvTimeout, PoolError)
