# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tests/03_pool/workers.ipynb

__all__ = ['compute_worker', 'echo_worker', 'pid_worker']

# %% nbs/tests/03_pool/workers.ipynb 2
from netrun.rpc.base import ChannelClosed

# %% nbs/tests/03_pool/workers.ipynb 3
def echo_worker(channel, worker_id):
    """Echo worker for pool testing."""
    try:
        while True:
            key, data = channel.recv()
            channel.send(f"echo:{key}", {"worker_id": worker_id, "data": data})
    except ChannelClosed:
        pass

# %% nbs/tests/03_pool/workers.ipynb 4
def compute_worker(channel, worker_id):
    """Compute worker for pool testing."""
    try:
        while True:
            key, data = channel.recv()
            if key == "square":
                channel.send("result", data * data)
            elif key == "double":
                channel.send("result", data * 2)
    except ChannelClosed:
        pass

# %% nbs/tests/03_pool/workers.ipynb 5
def pid_worker(channel, worker_id):
    """Worker that reports its process ID."""
    import os
    try:
        while True:
            key, data = channel.recv()
            channel.send("pid", {"worker_id": worker_id, "pid": os.getpid()})
    except ChannelClosed:
        pass
