# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/02_storage/test_serialization.pct.py

__all__ = ['test_all_methods_have_extensions', 'test_binary_extension', 'test_binary_round_trip', 'test_json_extension', 'test_json_list', 'test_json_round_trip', 'test_json_unicode', 'test_pickle_complex_types', 'test_pickle_extension', 'test_pickle_round_trip', 'test_str_extension', 'test_str_round_trip', 'test_validate_imports_json', 'test_validate_imports_pickle']

# %% pts/tests/02_storage/test_serialization.pct.py 2
import pytest

from netrun.storage._serialization import (
    SerializationMethod,
    serialize,
    deserialize,
    get_file_extension,
    validate_imports,
)

# %% pts/tests/02_storage/test_serialization.pct.py 4
def test_json_round_trip():
    value = {"key": [1, 2, 3], "nested": {"a": True}}
    data = serialize(value, SerializationMethod.json)
    assert isinstance(data, bytes)
    result = deserialize(data, SerializationMethod.json)
    assert result == value


def test_json_extension():
    assert get_file_extension(SerializationMethod.json) == ".json"

# %% pts/tests/02_storage/test_serialization.pct.py 6
def test_pickle_round_trip():
    value = {"data": [1, 2, 3], "set": {4, 5}}
    data = serialize(value, SerializationMethod.pickle)
    assert isinstance(data, bytes)
    result = deserialize(data, SerializationMethod.pickle)
    assert result == value


def test_pickle_extension():
    assert get_file_extension(SerializationMethod.pickle) == ".pkl"

# %% pts/tests/02_storage/test_serialization.pct.py 8
def test_str_round_trip():
    value = "hello world"
    data = serialize(value, SerializationMethod.str)
    assert isinstance(data, bytes)
    assert data == b"hello world"
    result = deserialize(data, SerializationMethod.str)
    assert result == value


def test_str_extension():
    assert get_file_extension(SerializationMethod.str) == ".txt"

# %% pts/tests/02_storage/test_serialization.pct.py 10
def test_binary_round_trip():
    value = b"\x00\x01\x02\xff"
    data = serialize(value, SerializationMethod.binary)
    assert data is value  # passthrough, no copy
    result = deserialize(data, SerializationMethod.binary)
    assert result == value


def test_binary_extension():
    assert get_file_extension(SerializationMethod.binary) == ".bin"

# %% pts/tests/02_storage/test_serialization.pct.py 12
def test_validate_imports_json():
    """JSON is stdlib, should never fail."""
    validate_imports(SerializationMethod.json)


def test_validate_imports_pickle():
    """Pickle is stdlib, should never fail."""
    validate_imports(SerializationMethod.pickle)

# %% pts/tests/02_storage/test_serialization.pct.py 14
def test_all_methods_have_extensions():
    """Every SerializationMethod should have a file extension."""
    for method in SerializationMethod:
        ext = get_file_extension(method)
        assert ext.startswith("."), f"{method} extension should start with '.', got {ext!r}"

# %% pts/tests/02_storage/test_serialization.pct.py 16
def test_json_unicode():
    value = {"emoji": "hello 🌍", "cjk": "你好"}
    data = serialize(value, SerializationMethod.json)
    result = deserialize(data, SerializationMethod.json)
    assert result == value


def test_json_list():
    value = [1, "two", 3.0, None, True]
    data = serialize(value, SerializationMethod.json)
    result = deserialize(data, SerializationMethod.json)
    assert result == value

# %% pts/tests/02_storage/test_serialization.pct.py 18
def test_pickle_complex_types():
    """Pickle should handle Python-specific types that JSON can't."""
    import datetime
    value = {
        "tuple": (1, 2, 3),
        "set": {4, 5, 6},
        "bytes": b"hello",
        "datetime": datetime.datetime(2024, 1, 1, 12, 0, 0),
    }
    data = serialize(value, SerializationMethod.pickle)
    result = deserialize(data, SerializationMethod.pickle)
    assert result == value
