# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/netrun/00_iutils/00_base.ipynb

__all__ = ['get_timestamp_utc', 'patch_to']

# %% nbs/netrun/00_iutils/00_base.ipynb 3
def patch_to(cls):
    """Patch a class to add a method."""

    def decorator(func):
        setattr(cls, func.__name__, func)
        return func

    return decorator

# %% nbs/netrun/00_iutils/00_base.ipynb 5
import datetime

# %% nbs/netrun/00_iutils/00_base.ipynb 6
def get_timestamp_utc():
    """Get the current timestamp in UTC."""
    return datetime.datetime.now(datetime.UTC)
