# AUTOGENERATED! DO NOT EDIT!

def main(text: str, ctx, print) -> str:
    """Transform text to uppercase."""
    import time
    
    print(f"Uppercasing {len(text)} chars")
    ctx.log("Uppercasing", input_length=len(text))
    time.sleep(1)  # Simulate processing
    result = text.upper()
    ctx.log("Uppercase complete")
    print(f"Done: {result[:40]}...")
    return result
